version: "3.8"

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - creatorhub-network

  auth-service:
    build:
      context: ./services/auth-service
    container_name: auth-service
    restart: unless-stopped
    env_file:
      - ./services/auth-service/.env
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    networks:
      - creatorhub-network

  product-service:
    build:
      context: ./services/product-service
    container_name: product-service
    restart: unless-stopped
    env_file:
      - ./services/product-service/.env
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
    networks:
      - creatorhub-network

  order-service:
    build:
      context: ./services/order-service
    container_name: order-service
    restart: unless-stopped
    env_file:
      - ./services/order-service/.env
    ports:
      - "3003:3003"
    depends_on:
      - mongodb
    networks:
      - creatorhub-network

  gateway-service:
    build:
      context: ./gateway
    container_name: gateway-service
    restart: unless-stopped
    env_file:
      - ./gateway/.env
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - product-service
      - order-service
    networks:
      - creatorhub-network

volumes:
  mongodb_data:

networks:
  creatorhub-network:
    driver: bridge
